version: "1.0.0"
services:
  server:
    build: .
    volumes:
      - /Users/batista/QinProject/OSUProgram/CS561WeatherDocker:/WeatherDocker
    environment:
      - USER=qin
    ports:
      - "3000:3000"
  client:
    image: "swiftlang/swift:nightly-focal"
    volumes:
      - /Users/batista/QinProject/OSUProgram/CS561WeatherDocker:/labs
    environment:
      - USER=will